### ISSUE TITLE
emoji by categories

### ISSUE THREAD

**Issue by MattiaRiola** [jeeftor/EmojiTaco#19]
Is it possible to split emoji by category to find faster what you need?

**Comment by jeeftor** [comment]
So right now I’m scraping from Unicode.org and I don’t believe they have categories which is somewhat annoying. 

The emoji come from here 
http://www.unicode.org/emoji/charts/full-emoji-list.html

And right now they only have descriptions. 

I have yet to find another source but if somebody comes up with one I can implement it. 

On the plus side because I pull from Unicode everything stays up to date. 

I looked at emojipedia I think at one point and it got me nowhere

**Comment by jeeftor** [comment]
Closing this issue due to no response yet :)
